// this file is generated by servgen util based on a template at 2021-06-26 10:37:24 +0300 MSK
package storage

import (
	"context"
	"github.com/travelata/auth/config"
	"github.com/travelata/auth/domain"
	"github.com/travelata/auth/logger"
	"github.com/travelata/auth/meta"
	kitCache "github.com/travelata/kit/cache/redis"
	kitStorage "github.com/travelata/kit/db"
	"github.com/travelata/kit/search"
	"golang.org/x/sync/errgroup"
)

// Adapter provides a contract to access a remote service
type Adapter interface {
	// Init - inits storage adapter
	Init(cfg *config.Storages) error
	// Close
	Close()
	GetAuthCodeStorage() domain.AuthCodeStorage
	GetUsersStorage() domain.UserStorage
	GetSessionsStorage() domain.SessionStorage
	GetSecurityStorage() domain.SecurityStorage
}

// container contains all the storages the adapter provides access to
type container struct {
	Db         *kitStorage.Storage
	ReadOnlyDB *kitStorage.Storage
	Cache      *kitCache.Redis
	Search     search.Search
}

// adapterImpl implements storage adapter
type adapterImpl struct {
	container       *container
	userStorage     *userStorageImpl
	securityStorage *securityStorageImpl
	sessionStorage  *sessionStorageImpl
	authCodeStorage *authCodeStorageImpl
}

// NewAdapter creates a new instance of the adapter
func NewAdapter() Adapter {
	a := &adapterImpl{
		container: &container{},
	}

	a.userStorage = newUserStorage(a.container)
	a.securityStorage = newSecurityStorage(a.container)
	a.sessionStorage = newSessionStorage(a.container)
	a.authCodeStorage = newAuthCodeStorage(a.container)

	return a
}

func (a *adapterImpl) Init(cfg *config.Storages) error {

	grp, _ := errgroup.WithContext(context.Background())

	// db master
	grp.Go(func() error {
		var err error
		a.container.Db, err = kitStorage.Open(cfg.Database.Master, logger.LF())
		if err != nil {
			return err
		}

		// applying migrations (leader only)
		if meta.Meta.Leader() && cfg.Database.MigPath != "" {
			db, _ := a.container.Db.Instance.DB()
			m := kitStorage.NewMigration(db, cfg.Database.MigPath, logger.LF())
			if err := m.Up(); err != nil {
				return err
			}
		}
		return nil
	})

	// db slave
	if cfg.Database.Slave != nil {
		grp.Go(func() error {
			var err error
			a.container.ReadOnlyDB, err = kitStorage.Open(cfg.Database.Slave, logger.LF())
			return err
		})
	}

	// Redis
	grp.Go(func() error {
		var err error
		a.container.Cache, err = kitCache.Open(cfg.Redis, logger.LF())
		return err
	})

	// Index search
	grp.Go(func() error {
		var err error
		a.container.Search, err = search.NewEs(cfg.Es, logger.LF())
		if err != nil {
			return err
		}
		err = a.userStorage.ensureIndex()
		if err != nil {
			return err
		}
		return err
	})

	if err := grp.Wait(); err != nil {
		logger.L().E(err).St().Err("init storage")
		return err
	}

	return nil
}

func (a *adapterImpl) GetAuthCodeStorage() domain.AuthCodeStorage {
	return a.authCodeStorage
}

func (a *adapterImpl) GetUsersStorage() domain.UserStorage {
	return a.userStorage
}

func (a *adapterImpl) GetSessionsStorage() domain.SessionStorage {
	return a.sessionStorage
}

func (a *adapterImpl) GetSecurityStorage() domain.SecurityStorage {
	return a.securityStorage
}

func (a *adapterImpl) Close() {
	a.container.Db.Close()
	a.container.ReadOnlyDB.Close()
	a.container.Cache.Close()
	a.container.Search.Close()
}
