// this file is generated by servgen util based on a template at 2021-06-26 10:37:24 +0300 MSK
package grpc

import (
	"github.com/travelata/auth/domain"
	"github.com/travelata/auth/logger"
	"github.com/travelata/auth/meta"
	pb "github.com/travelata/auth/proto"
	kitGrpc "github.com/travelata/kit/grpc"
)

// Server implements gRPC server
// Specify your protobuf contract in github.com/travelata/proto.git/auth
type Server struct {
	*kitGrpc.Server
	sampleService domain.SampleService

	pb.UnimplementedSampleServiceServer
}

// New creates a new gRPC server
func New(sampleService domain.SampleService) *Server {
	return &Server{sampleService: sampleService}
}

// Init initializes gRPC server
func (s *Server) Init(cfg *kitGrpc.ServerConfig) error {

	// grpc server
	gs, err := kitGrpc.NewServer(meta.Meta.ServiceCode(), logger.LF(), cfg)
	if err != nil {
		return err
	}
	s.Server = gs

	// register server
	pb.RegisterSampleServiceServer(s.Srv, s)
	return nil
}

// ListenAsync starts listening
// make sure it's executed as a goroutine
func (s *Server) ListenAsync() {
	go func() {
		err := s.Server.Listen()
		if err != nil {
			return
		}
	}()
}
